//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBild
    {
        public long BildID { get; set; }
        public long HotelID { get; set; }
        public int Reihenfolge { get; set; }
        public byte[] Bild { get; set; }
        public string Beschreibung { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
